# Generated by Django 3.0.6 on 2020-05-26 13:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mmt_map.models


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=mmt_map.models.feature_directory_path, verbose_name='Thumbnail Image')),
                ('thumbnail_copyright', models.CharField(blank=True, max_length=240)),
                ('popup_image', models.ImageField(blank=True, null=True, upload_to=mmt_map.models.feature_directory_path)),
                ('popup_audio_title', models.CharField(max_length=128)),
                ('weight', models.FloatField(default=1)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinates')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mmt_map.Theme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
