# Generated by Django 3.0.6 on 2020-05-26 13:22

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('mmt_map', '0002_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='popup_audio_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_file_feature', to='filer.File'),
        ),
    ]
