# Generated by Django 3.0.6 on 2020-05-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0003_point_popup_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='popup_audio_title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
