# Generated by Django 3.0.6 on 2020-05-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0005_auto_20200526_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='count',
        ),
    ]
