# Generated by Django 3.0.6 on 2020-05-27 12:07

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('mmt_map', '0007_auto_20200527_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='popup_audio_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_point_audio_file', to='filer.File'),
        ),
    ]
