# Generated by Django 3.0.6 on 2020-05-27 12:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import mmt_map.models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('mmt_map', '0008_auto_20200527_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=mmt_map.models.feature_directory_path, verbose_name='Thumbnail Image')),
                ('thumbnail_copyright', models.CharField(blank=True, max_length=240)),
                ('popup_image', models.ImageField(blank=True, null=True, upload_to=mmt_map.models.feature_directory_path)),
                ('popup_audio_title', models.CharField(blank=True, max_length=128)),
                ('weight', models.FloatField(default=1)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geometry')),
                ('popup_audio_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_polygon_audio_file', to='filer.File')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mmt_map.Theme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
