# Generated by Django 3.0.6 on 2020-05-27 14:50

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mmt_map', '0010_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_edited', models.DateField(auto_now=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('body_processed', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_document_author', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_document', to='mmt_map.Line')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_document_documents', to='mmt_map.Point')),
                ('polygon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_document_documents', to='mmt_map.Polygon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
