# Generated by Django 3.0.6 on 2020-05-27 14:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mmt_map.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mmt_map', '0011_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_edited', models.DateField(auto_now=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('file', models.ImageField(null=True, upload_to=mmt_map.models.feature_directory_path, verbose_name='Image')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('copyright', models.CharField(blank=True, max_length=140)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_image_author', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_image', to='mmt_map.Line')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_image_documents', to='mmt_map.Point')),
                ('polygon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_image_documents', to='mmt_map.Polygon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
