# Generated by Django 3.0.6 on 2020-05-27 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mmt_map', '0012_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='popup_audio_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_line_popup_audio_file', to='filer.File'),
        ),
        migrations.AlterField(
            model_name='point',
            name='popup_audio_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_point_popup_audio_file', to='filer.File'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='popup_audio_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_polygon_popup_audio_file', to='filer.File'),
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_edited', models.DateField(auto_now=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_audiofile_author', to=settings.AUTH_USER_MODEL)),
                ('file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_audiofile_audio_file', to='filer.File')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_audiofile', to='mmt_map.Line')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_audiofile_documents', to='mmt_map.Point')),
                ('polygon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_audiofile_documents', to='mmt_map.Polygon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
