# Generated by Django 3.0.6 on 2020-05-28 17:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0014_auto_20200528_0813'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='line',
            managers=[
                ('vector_tiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='point',
            managers=[
                ('vector_tiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='polygon',
            managers=[
                ('vector_tiles', django.db.models.manager.Manager()),
            ],
        ),
    ]
