# Generated by Django 3.0.6 on 2020-05-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0015_auto_20200528_1716'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='line',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='point',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='polygon',
            managers=[
            ],
        ),
    ]
