# Generated by Django 3.0.6 on 2020-05-31 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0016_auto_20200528_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_audiofiles', to='mmt_map.Line'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_audiofiles', to='mmt_map.Point'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='polygon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polygon_audiofiles', to='mmt_map.Polygon'),
        ),
        migrations.AlterField(
            model_name='document',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_documents', to='mmt_map.Line'),
        ),
        migrations.AlterField(
            model_name='document',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_documents', to='mmt_map.Point'),
        ),
        migrations.AlterField(
            model_name='document',
            name='polygon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polygon_documents', to='mmt_map.Polygon'),
        ),
        migrations.AlterField(
            model_name='image',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_images', to='mmt_map.Line'),
        ),
        migrations.AlterField(
            model_name='image',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_images', to='mmt_map.Point'),
        ),
        migrations.AlterField(
            model_name='image',
            name='polygon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polygon_images', to='mmt_map.Polygon'),
        ),
    ]
