# Generated by Django 3.0.6 on 2020-05-31 12:44

from django.db import migrations, models
import mmt_map.models


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0017_auto_20200531_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='thumbnail_copyright',
            new_name='banner_image_copyright',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='thumbnail_copyright',
            new_name='banner_image_copyright',
        ),
        migrations.RenameField(
            model_name='polygon',
            old_name='thumbnail_copyright',
            new_name='banner_image_copyright',
        ),
        migrations.RemoveField(
            model_name='line',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='point',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='polygon',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='line',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=mmt_map.models.feature_directory_path, verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='point',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=mmt_map.models.feature_directory_path, verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=mmt_map.models.feature_directory_path, verbose_name='Banner Image'),
        ),
    ]
