# Generated by Django 3.0.6 on 2020-07-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0022_auto_20200709_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='point',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='polygon',
            name='tags',
        ),
    ]
