# Generated by Django 3.0.6 on 2020-07-10 08:28

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('mmt_map', '0023_auto_20200709_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='tag_str',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='line',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='point',
            name='tag_str',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='point',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='tag_str',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='polygon',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
