# Generated by Django 3.0.6 on 2020-08-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0026_auto_20200715_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='point',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
