# Generated by Django 3.0.6 on 2020-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0027_auto_20200804_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='point',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='polygon',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
