# Generated by Django 3.1.13 on 2022-12-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('mmt_map', '0028_auto_20200806_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('tags', models.ManyToManyField(to='taggit.Tag')),
            ],
        ),
    ]
