# Generated by Django 3.2.18 on 2023-08-09 16:25

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Point = apps.get_model('mmt_map', 'Point')
    for row in Point.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])
    Line = apps.get_model('mmt_map', 'Line')
    for row in Line.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])
    Polygon = apps.get_model('mmt_map', 'Polygon')
    for row in Polygon.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0032_auto_20230809_1519'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
