# Generated by Django 3.2.18 on 2023-08-31 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0035_auto_20230828_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='line',
            name='attachments',
            field=models.CharField(blank=True, max_length=768),
        ),
        migrations.AddField(
            model_name='point',
            name='attachments',
            field=models.CharField(blank=True, max_length=768),
        ),
        migrations.AddField(
            model_name='polygon',
            name='attachments',
            field=models.CharField(blank=True, max_length=768),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiofiles', to='mmt_map.line'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiofiles', to='mmt_map.point'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='polygon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiofiles', to='mmt_map.polygon'),
        ),
        migrations.AlterField(
            model_name='document',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='mmt_map.line'),
        ),
        migrations.AlterField(
            model_name='document',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='mmt_map.point'),
        ),
        migrations.AlterField(
            model_name='document',
            name='polygon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='mmt_map.polygon'),
        ),
        migrations.AlterField(
            model_name='image',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='mmt_map.line'),
        ),
        migrations.AlterField(
            model_name='image',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='mmt_map.point'),
        ),
        migrations.AlterField(
            model_name='image',
            name='polygon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='mmt_map.polygon'),
        ),
    ]
