# Generated by Django 3.2.18 on 2024-03-23 09:22

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0036_auto_20230831_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
