# Generated by Django 3.2.18 on 2024-03-23 09:44

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0037_auto_20240323_0922'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension()
    ]
