# Generated by Django 3.2.18 on 2024-06-12 09:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import mmt_map.models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0014_folder_permission_choices'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('mmt_map', '0039_maplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=mmt_map.models.feature_directory_path, verbose_name='Banner Image')),
                ('banner_image_copyright', models.CharField(blank=True, max_length=240)),
                ('popup_image', models.ImageField(blank=True, null=True, upload_to=mmt_map.models.feature_directory_path)),
                ('thumbnail_url', models.CharField(blank=True, max_length=300)),
                ('popup_audio_title', models.CharField(blank=True, max_length=128)),
                ('popup_audio_slug', models.SlugField(blank=True, max_length=128)),
                ('weight', models.FloatField(default=1)),
                ('tag_str', models.CharField(blank=True, max_length=256)),
                ('published', models.BooleanField(default=False)),
                ('attachments', models.CharField(blank=True, max_length=768)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326, verbose_name='Points')),
                ('popup_audio_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_map_multipoint_popup_audio_file', to='filer.file')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mmt_map.theme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
