# Generated by Django 3.2.18 on 2024-06-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0040_multipoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='multipoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiofiles', to='mmt_map.multipoint'),
        ),
        migrations.AddField(
            model_name='document',
            name='multipoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='mmt_map.multipoint'),
        ),
        migrations.AddField(
            model_name='image',
            name='multipoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='mmt_map.multipoint'),
        ),
    ]
