# Generated by Django 3.2.18 on 2024-09-26 12:06

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0042_maplayer_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maplayer',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_duplicates=True, blank=True, editable=False, populate_from=['title', 'id']),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_duplicates=True, blank=True, editable=False, populate_from=['title', 'id']),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_duplicates=True, blank=True, editable=False, populate_from=['title', 'id']),
        ),
    ]
