# Generated by Django 3.2.18 on 2024-01-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_pages', '0006_page_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_instructions',
            field=models.BooleanField(default=False),
        ),
    ]
