# Generated by Django 3.2.18 on 2024-01-31 19:15

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_pages', '0008_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
